//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.Extensions.Configuration;
using System.Configuration;

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.sptransWS.digicon.com.br/", ConfigurationName="ServiceReference.PedidoCreditoService")]
    public interface PedidoCreditoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.consultarCartaoResponse> consultarCartaoAsync(ServiceReference.consultarCartao request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.gerarPedidoResponse> gerarPedidoAsync(ServiceReference.gerarPedido request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.confirmarPedidoResponse> confirmarPedidoAsync(ServiceReference.confirmarPedido request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.cancelarPedidoResponse> cancelarPedidoAsync(ServiceReference.cancelarPedido request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class keyAutenticacaoIn
    {
        
        private string senhaField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string senha
        {
            get
            {
                return this.senhaField;
            }
            set
            {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class gerarPedidoIn
    {
        
        private int codigoProdutoField;
        
        private bool codigoProdutoFieldSpecified;
        
        private int codigoTipoCreditoField;
        
        private bool codigoTipoCreditoFieldSpecified;
        
        private long numeroLogicoCartaoField;
        
        private bool numeroLogicoCartaoFieldSpecified;
        
        private int quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        private decimal valorTotalField;
        
        private bool valorTotalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoProduto
        {
            get
            {
                return this.codigoProdutoField;
            }
            set
            {
                this.codigoProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoProdutoSpecified
        {
            get
            {
                return this.codigoProdutoFieldSpecified;
            }
            set
            {
                this.codigoProdutoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoTipoCredito
        {
            get
            {
                return this.codigoTipoCreditoField;
            }
            set
            {
                this.codigoTipoCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoTipoCreditoSpecified
        {
            get
            {
                return this.codigoTipoCreditoFieldSpecified;
            }
            set
            {
                this.codigoTipoCreditoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long numeroLogicoCartao
        {
            get
            {
                return this.numeroLogicoCartaoField;
            }
            set
            {
                this.numeroLogicoCartaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroLogicoCartaoSpecified
        {
            get
            {
                return this.numeroLogicoCartaoFieldSpecified;
            }
            set
            {
                this.numeroLogicoCartaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int quantidade
        {
            get
            {
                return this.quantidadeField;
            }
            set
            {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantidadeSpecified
        {
            get
            {
                return this.quantidadeFieldSpecified;
            }
            set
            {
                this.quantidadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal valorTotal
        {
            get
            {
                return this.valorTotalField;
            }
            set
            {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorTotalSpecified
        {
            get
            {
                return this.valorTotalFieldSpecified;
            }
            set
            {
                this.valorTotalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class produtoOut
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        private decimal qtdeMaximaField;
        
        private bool qtdeMaximaFieldSpecified;
        
        private decimal qtdeMinimaField;
        
        private bool qtdeMinimaFieldSpecified;
        
        private decimal valorUnitarioField;
        
        private bool valorUnitarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal qtdeMaxima
        {
            get
            {
                return this.qtdeMaximaField;
            }
            set
            {
                this.qtdeMaximaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qtdeMaximaSpecified
        {
            get
            {
                return this.qtdeMaximaFieldSpecified;
            }
            set
            {
                this.qtdeMaximaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal qtdeMinima
        {
            get
            {
                return this.qtdeMinimaField;
            }
            set
            {
                this.qtdeMinimaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qtdeMinimaSpecified
        {
            get
            {
                return this.qtdeMinimaFieldSpecified;
            }
            set
            {
                this.qtdeMinimaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal valorUnitario
        {
            get
            {
                return this.valorUnitarioField;
            }
            set
            {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorUnitarioSpecified
        {
            get
            {
                return this.valorUnitarioFieldSpecified;
            }
            set
            {
                this.valorUnitarioFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class tipoCreditoOut
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        private produtoOut[] produtosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("produtos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public produtoOut[] produtos
        {
            get
            {
                return this.produtosField;
            }
            set
            {
                this.produtosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gerarPedidoOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(consultarCartaoOut))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class mensagemOut
    {
        
        private int codigoRetornoField;
        
        private bool codigoRetornoFieldSpecified;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRetornoSpecified
        {
            get
            {
                return this.codigoRetornoFieldSpecified;
            }
            set
            {
                this.codigoRetornoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class gerarPedidoOut : mensagemOut
    {
        
        private long numeroPedidoField;
        
        private bool numeroPedidoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long numeroPedido
        {
            get
            {
                return this.numeroPedidoField;
            }
            set
            {
                this.numeroPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroPedidoSpecified
        {
            get
            {
                return this.numeroPedidoFieldSpecified;
            }
            set
            {
                this.numeroPedidoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sptransWS.digicon.com.br/")]
    public partial class consultarCartaoOut : mensagemOut
    {
        
        private tipoCreditoOut[] tiposCreditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tiposCredito", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public tipoCreditoOut[] tiposCredito
        {
            get
            {
                return this.tiposCreditoField;
            }
            set
            {
                this.tiposCreditoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCartao", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class consultarCartao
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.keyAutenticacaoIn login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numeroCartao;
        
        public consultarCartao()
        {
        }
        
        public consultarCartao(ServiceReference.keyAutenticacaoIn login, long numeroCartao)
        {
            this.login = login;
            this.numeroCartao = numeroCartao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCartaoResponse", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class consultarCartaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.consultarCartaoOut @return;
        
        public consultarCartaoResponse()
        {
        }
        
        public consultarCartaoResponse(ServiceReference.consultarCartaoOut @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gerarPedido", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class gerarPedido
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.keyAutenticacaoIn login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gerarPedido", Namespace="http://service.sptransWS.digicon.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.gerarPedidoIn gerarPedidoIn;
        
        public gerarPedido()
        {
        }
        
        public gerarPedido(ServiceReference.keyAutenticacaoIn login, ServiceReference.gerarPedidoIn gerarPedidoIn)
        {
            this.login = login;
            this.gerarPedidoIn = gerarPedidoIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gerarPedidoResponse", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class gerarPedidoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.gerarPedidoOut @return;
        
        public gerarPedidoResponse()
        {
        }
        
        public gerarPedidoResponse(ServiceReference.gerarPedidoOut @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmarPedido", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class confirmarPedido
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.keyAutenticacaoIn login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numeroPedido;
        
        public confirmarPedido()
        {
        }
        
        public confirmarPedido(ServiceReference.keyAutenticacaoIn login, long numeroPedido)
        {
            this.login = login;
            this.numeroPedido = numeroPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmarPedidoResponse", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class confirmarPedidoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.mensagemOut @return;
        
        public confirmarPedidoResponse()
        {
        }
        
        public confirmarPedidoResponse(ServiceReference.mensagemOut @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarPedido", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class cancelarPedido
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.keyAutenticacaoIn login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numeroPedido;
        
        public cancelarPedido()
        {
        }
        
        public cancelarPedido(ServiceReference.keyAutenticacaoIn login, long numeroPedido)
        {
            this.login = login;
            this.numeroPedido = numeroPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarPedidoResponse", WrapperNamespace="http://service.sptransWS.digicon.com.br/", IsWrapped=true)]
    public partial class cancelarPedidoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sptransWS.digicon.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.mensagemOut @return;
        
        public cancelarPedidoResponse()
        {
        }
        
        public cancelarPedidoResponse(ServiceReference.mensagemOut @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface PedidoCreditoServiceChannel : ServiceReference.PedidoCreditoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PedidoCreditoServiceClient : System.ServiceModel.ClientBase<ServiceReference.PedidoCreditoService>, ServiceReference.PedidoCreditoService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PedidoCreditoServiceClient() : 
                base(PedidoCreditoServiceClient.GetDefaultBinding(), PedidoCreditoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PedidoCreditoServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoCreditoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PedidoCreditoServiceClient.GetBindingForEndpoint(endpointConfiguration), PedidoCreditoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoCreditoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PedidoCreditoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoCreditoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PedidoCreditoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoCreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.consultarCartaoResponse> consultarCartaoAsync(ServiceReference.consultarCartao request)
        {
            return base.Channel.consultarCartaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.gerarPedidoResponse> gerarPedidoAsync(ServiceReference.gerarPedido request)
        {
            return base.Channel.gerarPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.confirmarPedidoResponse> confirmarPedidoAsync(ServiceReference.confirmarPedido request)
        {
            return base.Channel.confirmarPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.cancelarPedidoResponse> cancelarPedidoAsync(ServiceReference.cancelarPedido request)
        {
            return base.Channel.cancelarPedidoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PedidoCreditoServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PedidoCreditoServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://proxypass-tivit-hom.eastus.cloudapp.azure.com:8081/sptransWS/PedidoCreditoService");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PedidoCreditoServiceClient.GetBindingForEndpoint(EndpointConfiguration.PedidoCreditoServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PedidoCreditoServiceClient.GetEndpointAddress(EndpointConfiguration.PedidoCreditoServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            PedidoCreditoServicePort,
        }
    }
}
